required_devices: 8
resume: false

no_test: false
test_only: false
debug: false
seed: 0
distributed: false
test_freq: 5
num_workers: 16

benchmark:
  name: "kinetics-400_lin-eval_112X112x32"

dataset:
  name: "kinetics"
  fold: 1
  batch_size: 64
  clip_duration: 1.0
  video_fps: 16.
  crop_size: 112
  transform: "msc+color"
  min_area: 0.08
  color: [0.4, 0.4, 0.4, 0.2]
  switch_channels: true
  normalize: false
  num_of_examples: 0
  train:
    split: "trainlist{fold:02d}"
    mode: "clip"
    clips_per_video: 1
    use_augmentation: true
    use_shuffle: true
    drop_last: true
  test:
    split: "testlist{fold:02d}"
    mode: "clip"
    clips_per_video: 1
    use_augmentation: false
    use_shuffle: false
    drop_last: false
  test_dense:
    split: "testlist{fold:02d}"
    mode: "video"
    clips_per_video: 10
    use_augmentation: false
    use_shuffle: false
    drop_last: false

optimizer:
  name: "adam"
  num_epochs: 40
  weight_decay: 0.0
  warmup_classifier: false
  lr:
    name: "multistep"
    base_lr: 0.01
    gamma: 0.3
    milestones: [10, 20, 30]

model:
  args:
    n_classes: 400
    feat_dim: 512
